"use client";
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { AccountEditor, DraftEditor, SettingsEditor } from './editors';
import type { Account, Post, Snapshot, SourceItem, Product, Notification } from './types';
const menus = ['Dashboard','Accounts','Content','Products','Scheduler','Analytics','Telegram','Settings'];
const descriptions: Record<string,string> = {Dashboard:'콘텐츠부터 게시까지, 운영 현황을 한눈에 확인하세요.',Accounts:'독립적인 브랜드와 Persona를 관리합니다.',Content:'수집한 소재를 검수 가능한 콘텐츠로 만듭니다.',Products:'상품 데이터와 제휴 연결 상태를 확인합니다.',Scheduler:'계정별 게시 예약과 실행 결과를 확인합니다.',Analytics:'실제 성과 데이터 연결을 준비합니다.',Telegram:'알림 기록과 허용된 관리자 명령을 확인합니다.',Settings:'안전한 운영을 위한 공통 기준을 설정합니다.'};
export type Api = <T=unknown>(path:string,method?:string,data?:unknown)=>Promise<T>;
export function Badge({value}:{value:string}) { return <span className={'badge '+(['FAILED','ERROR','AUTH_REQUIRED','OFFLINE','REJECT'].includes(value)?'bad':['MOCK','SCHEDULED','PAUSED','RETRY_WAIT','DRAFT','GENERATED'].includes(value)?'warn':'')}>{value}</span>; }
const date=(s:string|null|undefined)=>s?new Date(s).toLocaleString('ko-KR'):'—';
export default function Home(){
  const [token,setToken]=useState(''); const [menu,setMenu]=useState('Dashboard'); const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const [accounts,setAccounts]=useState<Account[]>([]);const [posts,setPosts]=useState<Post[]>([]);const [items,setItems]=useState<SourceItem[]>([]);const [products,setProducts]=useState<Product[]>([]);const [notes,setNotes]=useState<Notification[]>([]);
  const [sys,setSys]=useState<Snapshot|null>(null);const [prefs,setPrefs]=useState<Record<string,unknown>>({});const [logs,setLogs]=useState<Record<string,unknown>[]>([]);
  const [accountFilter,setAccountFilter]=useState(''); const [statusFilter,setStatusFilter]=useState('');const [contentTab,setContentTab]=useState('Drafts');const [editingAccount,setEditingAccount]=useState<Account|'new'|null>(null);const [editingPost,setEditingPost]=useState<Post|null>(null);
  const [analysis,setAnalysis]=useState<unknown>(null);const [commandResult,setCommandResult]=useState<unknown>(null);const [analytics,setAnalytics]=useState<Record<string,unknown>|null>(null);
  const api:Api=useCallback(async(path,method='GET',data)=>{
    const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);
    try{ const res=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:data===undefined?undefined:JSON.stringify(data),signal:controller.signal});const result=await res.json();if(!res.ok){if(res.status===401)setToken('');throw new Error(typeof result.detail==='string'?result.detail:JSON.stringify(result.detail));}return result; }finally{clearTimeout(timer);}
  },[token]);
  const refresh=useCallback(async()=>{const [a,p,c,pr,n,s,st,l]=await Promise.all([api<Account[]>('/accounts'),api<Post[]>('/posts'),api<SourceItem[]>('/content'),api<Product[]>('/products'),api<Notification[]>('/telegram'),api<Snapshot>('/system'),api<Record<string,unknown>>('/settings'),api<Record<string,unknown>[]>('/logs')]);setAccounts(a);setPosts(p);setItems(c);setProducts(pr);setNotes(n);setSys(s);setPrefs(st);setLogs(l);},[api]);
  useEffect(()=>{if(!token)return;let live=true;const load=()=>refresh().catch(e=>{if(live)setError(e.message);});void load();const timer=setInterval(load,5000);return()=>{live=false;clearInterval(timer);};},[token,refresh]);
  const action=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError(e instanceof Error?e.message:'요청을 처리하지 못했습니다.');}finally{setBusy(false);}};
  const name=(id:number)=>accounts.find(a=>a.id===id)?.name||String(id);
  async function signIn(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await api<{access_token:string}>('/auth/login','POST',Object.fromEntries(f));setToken(r.access_token);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  if(!token)return <div className="login"><section className="login-art"><div className="eyebrow" style={{color:'#64cbb0'}}>CONTENT OPERATIONS / 01</div><h1>Good content.<br/>Clear control.</h1><p>Threads Revenue Engine<br/>여러 계정의 콘텐츠, 검수, 예약을 하나의 공간에서.</p><div className="flow">01 &nbsp; 소재 수집 · 콘텐츠 작성<br/>02 &nbsp; 검수 · 승인 · 예약<br/>03 &nbsp; 게시 검증 · 운영 알림</div><p><Badge value="MOCK"/> &nbsp; 실제 외부 게시가 발생하지 않습니다.</p></section><section className="login-form"><form onSubmit={signIn}><div className="eyebrow">ADMIN WORKSPACE</div><h1>다시 오셨군요.</h1><p className="muted">관리자 계정으로 운영 공간에 로그인하세요.</p><label>관리자 아이디<input name="username" autoComplete="username" defaultValue="admin" required/></label><label>비밀번호<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} style={{width:'100%',marginTop:12}}>로그인</button><p className="muted" style={{fontSize:12}}>초기 계정은 환경변수로 설정합니다.<br/>세션은 브라우저 메모리에만 보관됩니다.</p></form></section></div>;
  const filtered=posts.filter(p=>(!accountFilter||p.account_id===Number(accountFilter))&&(!statusFilter||p.status===statusFilter));
  const stop=()=>{if(sys?.kill_switch)void action(()=>api('/system/resume','POST'));else if(window.confirm('신규 게시와 댓글을 중지할까요? 이미 전송 중인 요청은 취소할 수 없습니다.'))void action(()=>api('/system/stop','POST'));};
  const postCard=(p:Post)=><article className="post" key={p.id}><div className="panel-head"><div className="post-meta"><b>{name(p.account_id)}</b><span>#{p.id} · {p.goal} · {p.angle}</span></div><Badge value={p.status}/></div><div className="post-body">{p.body}</div><div className="post-meta"><span>{p.replies.length} replies</span><span>{p.remote_id||'아직 게시되지 않음'}</span><span>{date(p.scheduled_at)}</span></div>{p.error_code&&<p className="error">{p.error_code}</p>}{p.validation?.result&&<p className="muted">검수: {p.validation.result} · Human score {p.validation.human_score} · {[...(p.validation.errors||[]),...(p.validation.warnings||[])].join(', ')}</p>}<div className="actions" style={{marginTop:15}}>{['DRAFT','GENERATED','READY'].includes(p.status)&&<><button className="secondary" disabled={busy} onClick={()=>setEditingPost(p)}>수정 · 댓글</button><button className="secondary" disabled={busy} onClick={()=>action(()=>api(`/posts/${p.id}/validate`,'POST'))}>검사</button></>}{p.status==='READY'&&!p.approved_at&&<button disabled={busy} onClick={()=>action(()=>api(`/posts/${p.id}/approve`,'POST'))}>검토 완료 · 승인</button>}{p.status==='READY'&&p.approved_at&&<button disabled={busy} onClick={()=>setEditingPost(p)}>예약 설정</button>}{['SCHEDULED','RETRY_WAIT','DRAFT','GENERATED','READY','FAILED'].includes(p.status)&&!p.remote_id&&<button className="secondary" disabled={busy} onClick={()=>action(()=>api(`/posts/${p.id}/cancel`,'POST'))}>취소</button>}{['FAILED','RETRY_WAIT'].includes(p.status)&&<button disabled={busy} onClick={()=>action(()=>api(`/posts/${p.id}/retry`,'POST'))}>재시도</button>}</div></article>;
  return <div className="shell"><aside className="sidebar"><div className="brand">Threads<br/>Revenue Engine<small>OPERATIONS WORKSPACE</small></div><nav className="nav" aria-label="메인 메뉴">{menus.map((m,i)=><button key={m} className={menu===m?'active':''} onClick={()=>{setMenu(m);setError('');if(m==='Analytics')void api<Record<string,unknown>>('/analytics').then(setAnalytics).catch(e=>setError(e.message));}}><span>0{i+1}</span>{m}</button>)}</nav><div className="sidebar-bottom"><span className="dot"/> DEVELOPMENT<br/>Mock-first environment<br/>v0.1 · 기반 시스템</div></aside><main className="main"><header className="topbar"><span className="muted">Workspace &nbsp; / &nbsp; <b style={{color:'#29424c'}}>{menu}</b></span><div className="topbar-right"><Badge value="MOCK"/><span className="muted">Admin</span><button className="secondary" onClick={()=>action(async()=>{await api('/auth/logout','POST');setToken('');})}>로그아웃</button></div></header><div className="content"><div className="heading"><div><div className="eyebrow">THREADS REVENUE ENGINE</div><h1>{menu==='Dashboard'?'운영 대시보드':menu}</h1><p className="muted">{descriptions[menu]}</p></div><div className="actions"><button className="secondary" disabled={busy} onClick={()=>action(refresh)}>새로고침</button><button className="danger" disabled={busy} onClick={stop}>{sys?.kill_switch?'운영 재개':'긴급 중지'}</button></div></div><div className="notice">{sys?.kill_switch?'⏸ 전체 게시가 중지되었습니다. 관리자만 재개할 수 있습니다.':'MOCK MODE — 게시·댓글·알림은 로컬 시뮬레이션입니다. 실제 계정과 외부 API는 연결되지 않았습니다.'}</div>{error&&<p className="error" role="alert">{error}</p>}
  {menu==='Dashboard'&&<><div className="stats">{[['오늘 게시',sys?.today_posts,'UTC 기준'],['게시 성공',sys?.success,'ID 및 댓글 검증 완료'],['예약 대기',sys?.scheduled,'Worker 실행 대기'],['실패',sys?.failed,'확인이 필요한 작업']].map(([title,value,hint])=><div className="stat" key={String(title)}><span className="muted">{title}</span><strong>{value??'—'}</strong><small>{hint}</small></div>)}</div><div className="grid"><section className="panel"><div className="panel-head"><h2>계정 운영 현황</h2><span className="muted">{accounts.length} accounts</span></div><div className="table-wrap"><table><thead><tr><th>Account</th><th>Status</th><th>Daily limit</th><th>Token</th></tr></thead><tbody>{accounts.map(a=><tr key={a.id}><td><div className="account-name"><div className="avatar">{a.category.slice(0,1)}</div><div><b>{a.name}</b><small>@{a.username} · {a.category}</small></div></div></td><td><Badge value={a.status}/></td><td>{a.daily_post_limit} / day</td><td><span className="muted">{a.access_token_reference?'환경변수 참조':'미연결 · MOCK'}</span></td></tr>)}</tbody></table></div></section><section className="panel"><h2>시스템 상태</h2>{[['Worker',sys?.worker.status||'OFFLINE'],['Threads provider','MOCK'],['Telegram','MOCK'],['AI writer','MOCK']].map(([k,v])=><div className="status-row" key={k}><span>{k}</span><Badge value={v}/></div>)}<p className="muted" style={{fontSize:11}}>Heartbeat · {date(sys?.worker.last_seen)}</p><div className="status-row"><span>Queue waiting / processing</span><b>{sys?.queue.WAITING??0} / {sys?.queue.PROCESSING??0}</b></div><div className="status-row"><span>정보 / 제휴 게시</span><b>{sys?.information??0} / {sys?.affiliate??0}</b></div><div className="status-row"><span>Mock 알림 발송</span><b>{sys?.telegram.sent??0}</b></div></section></div><div className="grid"><section className="panel"><h2>최근 콘텐츠</h2>{posts.length?posts.slice(0,3).map(postCard):<div className="empty">첫 번째 콘텐츠를 준비해 보세요.<br/><button className="secondary" onClick={()=>setMenu('Content')}>콘텐츠 만들기 →</button></div>}</section><section className="panel"><h2>최근 운영 기록</h2>{logs.slice(0,7).map((l,i)=><div className="status-row" key={i}><div><b style={{fontSize:11}}>{String(l.action)}</b><p className="muted" style={{fontSize:10,margin:'5px 0'}}>{date(String(l.created_at))}</p></div><span className="muted" style={{fontSize:11}}>{String(l.actor)}</span></div>)}</section></div></>}
  {menu==='Accounts'&&<><div className="panel-head"><h2>브랜드 계정 · Account DNA</h2><button onClick={()=>setEditingAccount('new')}>+ 계정 추가</button></div><div className="cards">{accounts.map(a=><article className="card" key={a.id}><div className="panel-head"><div className="avatar">{a.category.slice(0,1)}</div><Badge value={a.status}/></div><h2>{a.name}</h2><p className="muted">@{a.username} · {a.category}<br/>{a.timezone}</p><div className="status-row"><span>게시 한도</span><b>{a.daily_post_limit} / day</b></div><div className="status-row"><span>제휴 비율</span><b>{Math.round(a.affiliate_ratio*100)}%</b></div><div className="actions" style={{marginTop:18}}><button className="secondary" onClick={()=>setEditingAccount(a)}>설정 · Persona</button><button disabled={busy} onClick={()=>action(()=>api(`/accounts/${a.id}`,'PATCH',accountInput(a,{status:a.status==='PAUSED'?'ONLINE':'PAUSED'})))}>{a.status==='PAUSED'?'재개':'일시 중지'}</button></div></article>)}</div></>}
  {menu==='Content'&&<><div className="tabs">{['Drafts','Raw Sources','New Source'].map(t=><button className={contentTab===t?'':'secondary'} key={t} onClick={()=>setContentTab(t)}>{t}</button>)}</div>{contentTab==='New Source'?<section className="panel"><h2>수동 소재 등록</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(async()=>{const sources=await api<{id:number}[]>('/sources');await api('/content','POST',{source_id:sources[0].id,source_title:f.get('title'),source_text:f.get('text'),category:f.get('category')});setContentTab('Raw Sources');});}}><label>소재 제목<input name="title" required maxLength={200}/></label><label>카테고리<input name="category" defaultValue="여행" required/></label><label>원문 · 근거<textarea name="text" required minLength={10}/></label><button disabled={busy}>소재 저장</button></form></section>:contentTab==='Raw Sources'?<section className="panel"><h2>수집 소재</h2>{items.map(c=><article className="post" key={c.id}><div className="panel-head"><b>{c.source_title}</b><Badge value={c.status}/></div><p className="muted">{c.source_text}</p><div className="actions"><button disabled={busy} className="secondary" onClick={()=>action(async()=>setAnalysis(await api(`/content/${c.id}/analyze`,'POST')))}>Mock 분석</button><select style={{width:190}} aria-label={`소재 ${c.id} 대상 계정`} value={accountFilter} onChange={e=>setAccountFilter(e.target.value)}><option value="">대상 계정 선택</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><button disabled={busy||c.status!=='ANALYZED'||!accountFilter} onClick={()=>action(async()=>{await api(`/content/${c.id}/generate`,'POST',{account_id:Number(accountFilter)});setContentTab('Drafts');})}>초안 생성</button></div></article>)}{analysis!==null&&<pre className="code">{JSON.stringify(analysis,null,2)}</pre>}</section>:<><div className="filters"><select aria-label="계정 필터" value={accountFilter} onChange={e=>setAccountFilter(e.target.value)}><option value="">전체 계정</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select aria-label="상태 필터" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">전체 상태</option>{['DRAFT','GENERATED','READY','SCHEDULED','SUCCESS','FAILED','CANCELLED'].map(s=><option key={s}>{s}</option>)}</select></div><section className="panel">{filtered.length?filtered.map(postCard):<div className="empty">표시할 콘텐츠가 없습니다. Raw Sources에서 소재를 분석하고 초안을 생성하세요.</div>}</section></>}</>}
  {menu==='Products'&&<section className="panel"><h2>등록 상품</h2><p className="muted">샘플 상품입니다. 실제 가격·재고·제휴 링크가 아닙니다. 기본 재사용 제한 {String(prefs.cooldown_days||14)}일.</p><div className="table-wrap"><table><thead><tr><th>상품</th><th>Provider</th><th>가격</th><th>평점 / 리뷰</th><th>Status</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><b>{p.name}</b><p className="muted">{p.category}</p></td><td>{p.provider}</td><td>₩{p.price?.toLocaleString()??'—'}</td><td>{p.rating??'—'} / {p.review_count??'—'}</td><td><Badge value="MOCK"/></td></tr>)}</tbody></table></div></section>}
  {menu==='Scheduler'&&<section className="panel"><div className="panel-head"><h2>게시 타임라인</h2><span className="muted">브라우저 시간대 · 수동 예약</span></div><div className="timeline">{posts.filter(p=>p.scheduled_at).sort((a,b)=>String(a.scheduled_at).localeCompare(String(b.scheduled_at))).map(p=><article key={p.id}><div className="post-meta"><b>{date(p.scheduled_at)}</b><span>{name(p.account_id)}</span></div>{postCard(p)}</article>)}</div>{!posts.some(p=>p.scheduled_at)&&<div className="empty">예약된 게시물이 없습니다. 검수와 승인 후 예약할 수 있습니다.</div>}</section>}
  {menu==='Analytics'&&<section className="panel"><h2>성과 데이터 연결 대기</h2><p className="muted">조회수, 클릭, 주문 및 수익은 수집된 데이터가 있을 때 표시됩니다. Phase 7 구현 전이며 임의의 수치를 채우지 않습니다.</p><div className="stats">{['Views','Clicks','Orders','Revenue'].map(s=><div className="stat" key={s}><span>{s}</span><strong>—</strong><small>미수집</small></div>)}</div><pre className="code">{JSON.stringify(analytics,null,2)}</pre></section>}
  {menu==='Telegram'&&<div className="grid"><section className="panel"><h2>Mock 알림 기록</h2>{notes.length?notes.map(n=><article className="post" key={n.id}><div className="panel-head"><span>{date(n.created_at)}</span><Badge value={n.state}/></div><pre className="code">{n.body}</pre><span className="muted">{n.remote_id}</span></article>):<div className="empty">게시 작업 후 알림이 기록됩니다.</div>}</section><section className="panel"><h2>관리자 명령 시뮬레이터</h2><p className="muted">실제 Telegram 전송은 비활성화되어 있습니다.</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void action(async()=>setCommandResult(await api('/telegram/command','POST',Object.fromEntries(f))));}}><label>허용 Chat ID<input name="chat_id" defaultValue="mock-admin" required/></label><label>명령<input name="text" defaultValue="/status" required/></label><button disabled={busy}>명령 실행</button></form><p className="muted">/help · /accounts · /today · /scheduled<br/>/failed · /pause ID · /resume ID · /retry ID</p>{commandResult!==null&&<pre className="code">{JSON.stringify(commandResult,null,2)}</pre>}</section></div>}
  {menu==='Settings'&&<SettingsEditor values={prefs} api={api} save={action} busy={busy}/>}
  </div></main>{editingAccount&&<AccountEditor account={editingAccount} api={api} save={action} close={()=>setEditingAccount(null)} busy={busy}/>} {editingPost&&<DraftEditor post={editingPost} api={api} save={action} close={()=>setEditingPost(null)} busy={busy}/>}</div>;
}
export function accountInput(a:Account, changes:Record<string,unknown>={}){return {name:a.name,username:a.username,category:a.category,timezone:a.timezone,daily_post_limit:a.daily_post_limit,daily_affiliate_limit:a.daily_affiliate_limit,minimum_interval:a.minimum_interval,affiliate_ratio:a.affiliate_ratio,reply_count:a.reply_count,content_ratios:a.content_ratios,status:a.status,access_token_reference:a.access_token_reference,...changes};}
