"""add vertical and sites

Revision ID: ee16810b132c
Revises: 001_initial_schema
Create Date: 2026-09-14 00:17:20.467511+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""add vertical and sites

Revision ID: ee16810b132c
Revises: 001_initial_schema
Create Date: 2026-09-14 00:17:20.467511+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee16810b132c'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vertical', sa.String(length=50), nullable=False, server_default='MOVIE'))
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_posts_vertical'), ['vertical'], unique=False)
        batch_op.create_foreign_key('fk_posts_site_id', 'sites', ['site_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_posts_site_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_posts_vertical'))
        batch_op.drop_column('site_id')
        batch_op.drop_column('vertical')

    # ### end Alembic commands ###
