"""initial"""
from alembic import op
import sqlalchemy as sa

revision = '98d0c541961e'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('daily_post_limit', sa.Integer(), nullable=False),
    sa.Column('daily_affiliate_limit', sa.Integer(), nullable=False),
    sa.Column('minimum_interval', sa.Integer(), nullable=False),
    sa.Column('affiliate_ratio', sa.Float(), nullable=False),
    sa.Column('content_ratios', sa.JSON(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('default_language', sa.String(length=20), nullable=False),
    sa.Column('access_token_reference', sa.String(length=100), nullable=True),
    sa.Column('token_expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('service', sa.String(length=30), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_sources',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempts',
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_address'), 'login_attempts', ['address'], unique=False)
    op.create_table('mock_remote_posts',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('remote_id', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('remote_id')
    )
    op.create_table('products',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_product_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('affiliate_url', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('delivery_type', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_product_id')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('worker_heartbeats',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('worker_leases',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('until', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('content_items',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_title', sa.String(length=200), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['content_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('personas',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('target_description', sa.Text(), nullable=False),
    sa.Column('primary_desire', sa.Text(), nullable=False),
    sa.Column('secondary_desire', sa.Text(), nullable=False),
    sa.Column('pain_points', sa.JSON(), nullable=False),
    sa.Column('tone', sa.String(length=80), nullable=False),
    sa.Column('speech_style', sa.String(length=30), nullable=False),
    sa.Column('emoji_level', sa.Integer(), nullable=False),
    sa.Column('hook_preferences', sa.JSON(), nullable=False),
    sa.Column('prohibited_styles', sa.JSON(), nullable=False),
    sa.Column('content_objectives', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('content_analyses',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id')
    )
    op.create_table('posts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('goal', sa.String(length=30), nullable=False),
    sa.Column('angle', sa.String(length=30), nullable=False),
    sa.Column('hook_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remote_id', sa.String(length=120), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mock', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('remote_id')
    )
    op.create_index(op.f('ix_posts_account_id'), 'posts', ['account_id'], unique=False)
    op.create_index(op.f('ix_posts_scheduled_at'), 'posts', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_table('account_product_history',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('angle', sa.String(length=30), nullable=False),
    sa.Column('hook_type', sa.String(length=30), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('jobs',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_token', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_index(op.f('ix_jobs_due_at'), 'jobs', ['due_at'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_table('notifications',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=100), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('remote_id', sa.String(length=100), nullable=True),
    sa.Column('mock', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key')
    )
    op.create_table('post_replies',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('remote_id', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'position')
    )
    op.create_table('publication_reservations',
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('fingerprint'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('job_attempts',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_attempts')
    op.drop_table('publication_reservations')
    op.drop_table('post_replies')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_due_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('account_product_history')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_scheduled_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_account_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_table('content_analyses')
    op.drop_table('sessions')
    op.drop_table('personas')
    op.drop_table('content_items')
    op.drop_table('worker_leases')
    op.drop_table('worker_heartbeats')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('products')
    op.drop_table('mock_remote_posts')
    op.drop_index(op.f('ix_login_attempts_address'), table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_table('content_sources')
    op.drop_table('audit_logs')
    op.drop_table('accounts')
    # ### end Alembic commands ###
